<?php

/**
 * Copyright (c) 2016, 2024, 5 Mode's contributors
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither 5 Mode nor the names of its contributors 
 *       may be used to endorse or promote products derived from this software 
 *       without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * HC_const.inc
 * 
 * Http Console constant file.
 *
 * @author Daniele Bonini <my25mb@aol.com>
 * @copyrights (c) 2016, 2024, 5 Mode     
 * @license https://opensource.org/licenses/BSD-3-Clause 
 */

if (!defined("HC_BR")) {
  define('HC_BR', "<br>");
}
if (!defined("HC_CN")) {
  define('HC_CN', "zh-CN");
}
if (!defined("HC_EN")) {
  define('HC_EN', "en-US");
}
if (!defined("HC_ES")) {
  define('HC_ES', "es-ES");
}
if (!defined("HC_FR")) {
  define('HC_FR', "fr-FR");
}
if (!defined("HC_HYPHEN")) {
  define('HC_HYPHEN', "-");
}
if (!defined("HC_IT")) {
  define('HC_IT', "it-IT");
}
if (!defined("HC_PIPE")) {
  define('HC_PIPE', "|");
}
if (!defined("HC_FILE_PIPE")) {
  define('HC_FILE_PIPE', ">");
}
if (!defined("HC_SLASH")) {
  define('HC_SLASH', "/");
}
if (!defined("HC_SPACE")) {
  define('HC_SPACE', " ");
}
if (!defined("HC_STR")) {
  define('HC_STR', "");
}
if (!defined("HC_TILDE")) {
  define('HC_TILDE', "~");
}
if (!defined("HC_UNDERSCORE")) {
  define('HC_UNDERSCORE', "_");
}
if (!defined("HC_UPLOAD_ERR_OK")) {
  define('HC_UPLOAD_ERR_OK', 0);
}
if (!defined("HC_UPLOAD_ERR_INI_SIZE")) {
  define('HC_UPLOAD_ERR_INI_SIZE', 1);
}
if (!defined("HC_UPLOAD_ERR_FORM_SIZE")) {
  define('HC_UPLOAD_ERR_FORM_SIZE', 2);
}
if (!defined("HC_UPLOAD_ERR_PARTIAL")) {
  define('HC_UPLOAD_ERR_PARTIAL', 3);
}
if (!defined("HC_UPLOAD_ERR_NO_FILE")) {
  define('HC_UPLOAD_ERR_NO_FILE', 4);
}
if (!defined("HC_UPLOAD_ERR_NO_TMP_DIR")) {
  define('HC_UPLOAD_ERR_NO_TMP_DIR', 6);
}
if (!defined("HC_UPLOAD_ERR_CANT_WRITE")) {
  define('HC_UPLOAD_ERR_CANT_WRITE', 7);
}
if (!defined("HC_UPLOAD_ERR_EXTENSION")) {
  define('HC_UPLOAD_ERR_EXTENSION', 8);
}
