<?php

/**
 * Copyright 2021, 2024 5 Mode
 *
 * This file is part of Http Console.
 *
 * Http Console is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Http Console is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.  
 * 
 * You should have received a copy of the GNU General Public License
 * along with Http Console. If not, see <https://www.gnu.org/licenses/>.
 *
 * HC_const.inc
 * 
 * Http Console constant file.
 *
 * @author Daniele Bonini <my25mb@aol.com>
 * @copyrights (c) 2021, 2024, 5 Mode     
 */

if (!defined("HC_BR")) {
  define('HC_BR', "<br>");
}
if (!defined("HC_CN")) {
  define('HC_CN', "zh-CN");
}
if (!defined("HC_EN")) {
  define('HC_EN', "en-US");
}
if (!defined("HC_ES")) {
  define('HC_ES', "es-ES");
}
if (!defined("HC_FR")) {
  define('HC_FR', "fr-FR");
}
if (!defined("HC_HYPHEN")) {
  define('HC_HYPHEN', "-");
}
if (!defined("HC_IT")) {
  define('HC_IT', "it-IT");
}
if (!defined("HC_PIPE")) {
  define('HC_PIPE', "|");
}
if (!defined("HC_FILE_PIPE")) {
  define('HC_FILE_PIPE', ">");
}
if (!defined("HC_SLASH")) {
  define('HC_SLASH', "/");
}
if (!defined("HC_SPACE")) {
  define('HC_SPACE', " ");
}
if (!defined("HC_STR")) {
  define('HC_STR', "");
}
if (!defined("HC_TILDE")) {
  define('HC_TILDE', "~");
}
if (!defined("HC_UNDERSCORE")) {
  define('HC_UNDERSCORE', "_");
}
if (!defined("HC_UPLOAD_ERR_OK")) {
  define('HC_UPLOAD_ERR_OK', 0);
}
if (!defined("HC_UPLOAD_ERR_INI_SIZE")) {
  define('HC_UPLOAD_ERR_INI_SIZE', 1);
}
if (!defined("HC_UPLOAD_ERR_FORM_SIZE")) {
  define('HC_UPLOAD_ERR_FORM_SIZE', 2);
}
if (!defined("HC_UPLOAD_ERR_PARTIAL")) {
  define('HC_UPLOAD_ERR_PARTIAL', 3);
}
if (!defined("HC_UPLOAD_ERR_NO_FILE")) {
  define('HC_UPLOAD_ERR_NO_FILE', 4);
}
if (!defined("HC_UPLOAD_ERR_NO_TMP_DIR")) {
  define('HC_UPLOAD_ERR_NO_TMP_DIR', 6);
}
if (!defined("HC_UPLOAD_ERR_CANT_WRITE")) {
  define('HC_UPLOAD_ERR_CANT_WRITE', 7);
}
if (!defined("HC_UPLOAD_ERR_EXTENSION")) {
  define('HC_UPLOAD_ERR_EXTENSION', 8);
}
